class CountryUtils {
  static const Map<String, String> _countryCodeMap = {
    'united states': 'US',
    'usa': 'US',
    'united states of america': 'US',
    'india': 'IN',
    'japan': 'JP',
    'germany': 'DE',
    'france': 'FR',
    'united kingdom': 'GB',
    'uk': 'GB',
    'canada': 'CA',
    'australia': 'AU',
    'brazil': 'BR',
    'china': 'CN',
    'russia': 'RU',
    'south korea': 'KR',
    'italy': 'IT',
    'spain': 'ES',
    'netherlands': 'NL',
    'switzerland': 'CH',
    'sweden': 'SE',
    'norway': 'NO',
    'denmark': 'DK',
    'finland': 'FI',
    'poland': 'PL',
    'czech republic': 'CZ',
    'austria': 'AT',
    'belgium': 'BE',
    'ireland': 'IE',
    'portugal': 'PT',
    'greece': 'GR',
    'hungary': 'HU',
    'romania': 'RO',
    'bulgaria': 'BG',
    'croatia': 'HR',
    'slovenia': 'SI',
    'slovakia': 'SK',
    'lithuania': 'LT',
    'latvia': 'LV',
    'estonia': 'EE',
    'luxembourg': 'LU',
    'malta': 'MT',
    'cyprus': 'CY',
    'new zealand': 'NZ',
    'singapore': 'SG',
    'malaysia': 'MY',
    'thailand': 'TH',
    'vietnam': 'VN',
    'indonesia': 'ID',
    'philippines': 'PH',
    'taiwan': 'TW',
    'hong kong': 'HK',
    'south africa': 'ZA',
    'egypt': 'EG',
    'nigeria': 'NG',
    'kenya': 'KE',
    'ghana': 'GH',
    'morocco': 'MA',
    'tunisia': 'TN',
    'algeria': 'DZ',
    'libya': 'LY',
    'sudan': 'SD',
    'ethiopia': 'ET',
    'uganda': 'UG',
    'tanzania': 'TZ',
    'zambia': 'ZM',
    'zimbabwe': 'ZW',
    'botswana': 'BW',
    'namibia': 'NA',
    'mozambique': 'MZ',
    'angola': 'AO',
    'congo': 'CG',
    'cameroon': 'CM',
    'chad': 'TD',
    'niger': 'NE',
    'mali': 'ML',
    'burkina faso': 'BF',
    'senegal': 'SN',
    'guinea': 'GN',
    'sierra leone': 'SL',
    'liberia': 'LR',
    'ivory coast': 'CI',
    'gambia': 'GM',
    'guinea-bissau': 'GW',
    'cape verde': 'CV',
    'mauritania': 'MR',
    'western sahara': 'EH',
    'equatorial guinea': 'GQ',
    'gabon': 'GA',
    'central african republic': 'CF',
    'democratic republic of the congo': 'CD',
    'rwanda': 'RW',
    'burundi': 'BI',
    'comoros': 'KM',
    'seychelles': 'SC',
    'madagascar': 'MG',
    'mauritius': 'MU',
    'reunion': 'RE',
    'mayotte': 'YT',
    'djibouti': 'DJ',
    'somalia': 'SO',
    'eritrea': 'ER',
    'yemen': 'YE',
    'oman': 'OM',
    'united arab emirates': 'AE',
    'qatar': 'QA',
    'bahrain': 'BH',
    'kuwait': 'KW',
    'iraq': 'IQ',
    'iran': 'IR',
    'afghanistan': 'AF',
    'pakistan': 'PK',
    'bangladesh': 'BD',
    'sri lanka': 'LK',
    'maldives': 'MV',
    'nepal': 'NP',
    'bhutan': 'BT',
    'myanmar': 'MM',
    'laos': 'LA',
    'cambodia': 'KH',
    'brunei': 'BN',
    'east timor': 'TL',
    'papua new guinea': 'PG',
    'fiji': 'FJ',
    'solomon islands': 'SB',
    'vanuatu': 'VU',
    'new caledonia': 'NC',
    'french polynesia': 'PF',
    'samoa': 'WS',
    'tonga': 'TO',
    'kiribati': 'KI',
    'tuvalu': 'TV',
    'nauru': 'NR',
    'palau': 'PW',
    'marshall islands': 'MH',
    'micronesia': 'FM',
    'northern mariana islands': 'MP',
    'guam': 'GU',
    'american samoa': 'AS',
    'cook islands': 'CK',
    'niue': 'NU',
    'tokelau': 'TK',
    'pitcairn': 'PN',
    'wallis and futuna': 'WF',
    'french southern territories': 'TF',
    'british indian ocean territory': 'IO',
    'christmas island': 'CX',
    'cocos islands': 'CC',
    'norfolk island': 'NF',
    'heard island and mcdonald islands': 'HM',
    'bouvet island': 'BV',
    'south georgia and the south sandwich islands': 'GS',
    'falkland islands': 'FK',
    'svalbard and jan mayen': 'SJ',
    'greenland': 'GL',
    'faroe islands': 'FO',
    'iceland': 'IS',
    'liechtenstein': 'LI',
    'monaco': 'MC',
    'san marino': 'SM',
    'vatican city': 'VA',
    'andorra': 'AD',
    'moldova': 'MD',
    'ukraine': 'UA',
    'belarus': 'BY',
    'georgia': 'GE',
    'armenia': 'AM',
    'azerbaijan': 'AZ',
    'kazakhstan': 'KZ',
    'uzbekistan': 'UZ',
    'turkmenistan': 'TM',
    'tajikistan': 'TJ',
    'kyrgyzstan': 'KG',
    'mongolia': 'MN',
    'north korea': 'KP',
    'macau': 'MO',
    'serbia': 'RS',
    'montenegro': 'ME',
    'kosovo': 'XK',
    'north macedonia': 'MK',
    'albania': 'AL',
    'bosnia and herzegovina': 'BA',
  };

  static String getCountryCode(String countryName) {
    final normalizedCountry = countryName.toLowerCase().trim();
    return _countryCodeMap[normalizedCountry] ?? 'UN';
  }
}
